name: Issue Labeler

on:
  issues:
    types: [opened]

jobs:
  predict:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: [ghcr.io/daavoo/model-pyday-bcn-2021:solution]
    steps:
      - name: Model Predict
        run: docker run ${{ matrix.model }} ${{ github.event.issue.title }} ${{ github.event.issue.body }}
